"""Licences, provenance records and ATTRIBUTIONS.md.

THE RULE: nothing is stored or shown without knowing where it came from and
under what licence. A licence string this module does not recognise is treated
as "cannot be determined", and the pipeline refuses the asset rather than
guessing. Licences are keyed by SPDX identifier where one exists, and by a
`LicenseRef-` identifier (the SPDX convention for everything else) where not.

A repository's overall licence is NOT assumed to cover every file in it: each
asset carries its own record, taken from the most specific source available.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path


@dataclass(frozen=True)
class License:
    spdx: str
    name: str
    url: str
    attribution_required: bool
    share_alike: bool
    non_commercial: bool


KNOWN_LICENSES: dict[str, License] = {lic.spdx: lic for lic in [
    License("CC0-1.0", "Creative Commons Zero 1.0 (public domain dedication)",
            "https://creativecommons.org/publicdomain/zero/1.0/", False, False, False),
    License("CC-BY-4.0", "Creative Commons Attribution 4.0 International",
            "https://creativecommons.org/licenses/by/4.0/", True, False, False),
    License("CC-BY-3.0", "Creative Commons Attribution 3.0 Unported",
            "https://creativecommons.org/licenses/by/3.0/", True, False, False),
    License("CC-BY-SA-4.0", "Creative Commons Attribution-ShareAlike 4.0 International",
            "https://creativecommons.org/licenses/by-sa/4.0/", True, True, False),
    License("CC-BY-SA-3.0", "Creative Commons Attribution-ShareAlike 3.0 Unported",
            "https://creativecommons.org/licenses/by-sa/3.0/", True, True, False),
    License("CC-BY-SA-2.1-JP", "Creative Commons Attribution-ShareAlike 2.1 Japan",
            "https://creativecommons.org/licenses/by-sa/2.1/jp/", True, True, False),
    License("CC-BY-NC-4.0", "Creative Commons Attribution-NonCommercial 4.0 International",
            "https://creativecommons.org/licenses/by-nc/4.0/", True, False, True),
    License("CC-BY-NC-SA-4.0", "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International",
            "https://creativecommons.org/licenses/by-nc-sa/4.0/", True, True, True),
    License("LicenseRef-Public-Domain-US-Gov", "Public domain (work of the U.S. Government)",
            "https://www.usa.gov/government-copyright", False, False, False),
    # PubChem: "NCBI itself places no restrictions on the use or distribution
    # of the data contained therein." Depositor records can differ, which is
    # why only PubChem-COMPUTED data (formula, SMILES, 3D conformers) is used.
    License("LicenseRef-NCBI-Data-Policy", "NCBI/PubChem data policy (no NCBI-imposed restrictions)",
            "https://www.ncbi.nlm.nih.gov/home/about/policies/", False, False, False),
    # Geometry this project computes itself (cells, simulations, molecule
    # meshes built from structure data). No third-party rights involved.
    License("LicenseRef-Generated", "Generated by 3D Education Engine (no third-party content)",
            "docs/provenance.md#generated-content", False, False, False),
]}

# Licences the pipeline accepts without asking. NonCommercial licences are
# known but NOT accepted by default: an educational product may still be sold.
DEFAULT_ACCEPTED = {
    "CC0-1.0", "CC-BY-4.0", "CC-BY-3.0", "CC-BY-SA-4.0", "CC-BY-SA-3.0",
    "CC-BY-SA-2.1-JP", "LicenseRef-Public-Domain-US-Gov", "LicenseRef-NCBI-Data-Policy",
    "LicenseRef-Generated",
}

PROVENANCE_FIELDS = ("provider", "url", "source_id", "creator", "license", "license_url",
                     "attribution", "download_date", "modification_status")

MODIFICATION_STATUSES = {"original", "converted", "converted+decimated", "extracted",
                         "extracted+converted+decimated", "generated", "computed-from-data"}


class LicenseError(ValueError):
    """The licence is unknown, missing, or not accepted by the policy."""


@dataclass
class ProvenanceRecord:
    provider: str
    url: str
    source_id: str
    creator: str
    license: str
    license_url: str
    attribution: str
    download_date: str
    modification_status: str

    def to_manifest(self) -> dict:
        return asdict(self)


def check_license(spdx: str, accepted: set[str] | None = None) -> License:
    """The License for `spdx`, or LicenseError. Never guesses."""
    if not spdx:
        raise LicenseError("no licence given: the licence cannot be determined")
    lic = KNOWN_LICENSES.get(spdx)
    if lic is None:
        raise LicenseError(f"unrecognised licence {spdx!r}: the licence cannot be determined")
    if spdx not in (DEFAULT_ACCEPTED if accepted is None else accepted):
        raise LicenseError(f"licence {spdx} ({lic.name}) is known but not accepted by the policy")
    return lic


def generated_provenance(what: str, based_on: str = "") -> ProvenanceRecord:
    """Provenance for geometry the engine builds itself."""
    return ProvenanceRecord(
        provider="3D Education Engine (procedural)",
        url="local://generated",
        source_id=what,
        creator="3D Education Engine",
        license="LicenseRef-Generated",
        license_url=KNOWN_LICENSES["LicenseRef-Generated"].url,
        attribution=("Educational model generated procedurally by 3D Education Engine"
                     + (f", based on {based_on}" if based_on else "") + "."),
        download_date=date.today().isoformat(),
        modification_status="generated",
    )


def attributions_markdown(rows: list[dict]) -> str:
    """ATTRIBUTIONS.md body from provenance rows (repository.provenance())."""
    third_party = [r for r in rows if r["license"] != "LicenseRef-Generated"]
    generated = [r for r in rows if r["license"] == "LicenseRef-Generated"]
    out = [
        "# Attributions",
        "",
        "Generated by `scripts/build_index.py` from the provenance stored with every",
        "asset. Do not edit by hand: change the asset's manifest and rebuild.",
        "",
        "## Third-party content",
        "",
    ]
    if not third_party:
        out.append("_None yet._")
    by_model: dict[str, list[dict]] = {}
    for r in third_party:
        by_model.setdefault(r["model_id"], []).append(r)
    for model_id in sorted(by_model):
        out.append(f"### `{model_id}`")
        out.append("")
        for r in by_model[model_id]:
            lic = KNOWN_LICENSES.get(r["license"])
            lic_name = lic.name if lic else r["license"]
            out += [
                f"- **{r['attribution_text']}**",
                f"  - Source: {r['source_name']} — [{r['source_id']}]({r['source_url']})",
                f"  - Creator: {r['creator']}",
                f"  - Licence: [{lic_name}]({r['license_url']})",
                f"  - Retrieved: {r['download_date']}; modifications: {r['modification_status']}",
            ]
            if lic and lic.share_alike:
                out.append("  - Share-alike: adaptations of this asset must be released under the same licence.")
        out.append("")
    out += ["## Generated by this project", ""]
    if generated:
        for r in sorted(generated, key=lambda r: r["model_id"]):
            out.append(f"- `{r['model_id']}` — {r['attribution_text']}")
    else:
        out.append("_None._")
    out.append("")
    return "\n".join(out)


def write_attributions(rows: list[dict], path: Path) -> None:
    path.write_text(attributions_markdown(rows), encoding="utf-8")
